<?php

declare(strict_types=1);

return [
    'permissions' => [
        // Plataforma
        'platform.dashboard',
        'platform.companies.view',
        'platform.companies.manage',
        'platform.users.view',
        'platform.users.manage',
        'platform.documents.view',
        'platform.documents.manage',
        'platform.settings.manage',

        // Empresa de seguridad
        'company.dashboard',
        'company.clients.view',
        'company.clients.manage',
        'company.users.assign',
        'company.settings.manage',
        'company.supervision.view',

        // Cliente / censo (fase 1+)
        'client.structures.manage',
        'client.members.manage',
        'client.pets.manage',
        'client.vehicles.manage',
        'client.authorizations.manage',
        'client.app_users.manage',
        'client.users.manage',

        // Portería operativa
        'access.operations',
        'access.dashboard',
        'access.manage.blocklist',
        'access.manage.visitors',
        'access.manage.vehicles',
        'access.manage.vehicle_access',
        'access.register.entry',
        'access.register.exit',
        'access.manage.pre_authorizations',
        'access.manage.correspondence',
        'access.manage.guard_logs',
        'access.manage.locations',
        'access.manage.buildings',
        'access.manage.housing_units',
        'access.manage.residents',
        'access.manage.supervision',
        'access.manage.supervision_codes',
        'access.view.reports',
        'access.view.audit',
        'access.manage.turnos',
        'access.manage.zones',
        'client.zones.book',

        // Residente
        'resident.portal.access',
    ],

    'roles' => [
        'super-admin' => [
            'platform.dashboard',
            'platform.companies.view',
            'platform.companies.manage',
            'platform.users.view',
            'platform.users.manage',
            'platform.documents.view',
            'platform.documents.manage',
            'platform.settings.manage',
        ],

        'company-admin' => [
            'company.dashboard',
            'company.clients.view',
            'company.clients.manage',
            'company.users.assign',
            'company.settings.manage',
            'company.supervision.view',
            'client.structures.manage',
            'client.members.manage',
            'client.pets.manage',
            'client.vehicles.manage',
            'client.authorizations.manage',
            'client.app_users.manage',
            'client.users.manage',
            'access.operations',
            'access.dashboard',
            'access.manage.blocklist',
            'access.manage.locations',
            'access.manage.buildings',
            'access.manage.housing_units',
            'access.manage.residents',
            'access.manage.visitors',
            'access.manage.vehicles',
            'access.manage.vehicle_access',
            'access.register.entry',
            'access.register.exit',
            'access.manage.pre_authorizations',
            'access.manage.correspondence',
            'access.manage.guard_logs',
            'access.manage.supervision',
            'access.manage.supervision_codes',
            'access.view.reports',
            'access.view.audit',
            'access.manage.turnos',
            'access.manage.zones',
        ],

        'client-admin' => [
            'client.structures.manage',
            'client.members.manage',
            'client.pets.manage',
            'client.vehicles.manage',
            'client.authorizations.manage',
            'client.app_users.manage',
            'client.users.manage',
            'access.operations',
            'access.dashboard',
            'access.manage.blocklist',
            'access.manage.locations',
            'access.manage.buildings',
            'access.manage.housing_units',
            'access.manage.residents',
            'access.manage.visitors',
            'access.manage.vehicles',
            'access.manage.vehicle_access',
            'access.register.entry',
            'access.register.exit',
            'access.manage.pre_authorizations',
            'access.manage.correspondence',
            'access.manage.guard_logs',
            'access.manage.supervision',
            'access.manage.supervision_codes',
            'access.view.reports',
            'access.view.audit',
            'access.manage.turnos',
            'access.manage.zones',
        ],

        'guardia' => [
            'access.operations',
            'access.dashboard',
            'access.manage.blocklist',
            'access.register.entry',
            'access.register.exit',
            'access.manage.visitors',
            'access.manage.vehicles',
            'access.manage.vehicle_access',
            'access.manage.residents',
            'access.manage.correspondence',
            'access.manage.guard_logs',
            'access.manage.supervision',
            'access.manage.supervision_codes',
            'access.view.reports',
            'access.manage.turnos',
            'access.manage.zones',
        ],

        'supervisor' => [
            'access.operations',
            'access.dashboard',
            'access.manage.blocklist',
            'access.register.entry',
            'access.register.exit',
            'access.manage.visitors',
            'access.manage.vehicles',
            'access.manage.vehicle_access',
            'access.manage.residents',
            'access.manage.correspondence',
            'access.manage.guard_logs',
            'access.manage.supervision',
            'access.manage.supervision_codes',
            'access.view.reports',
            'access.view.audit',
            'access.manage.turnos',
            'access.manage.zones',
        ],

        'resident' => [
            'resident.portal.access',
            'access.manage.pre_authorizations',
            'client.zones.book',
        ],

        // Compatibilidad temporal con roles existentes
        'admin-accesos' => [
            'client.structures.manage',
            'client.members.manage',
            'client.pets.manage',
            'client.vehicles.manage',
            'client.authorizations.manage',
            'client.app_users.manage',
            'client.users.manage',
            'access.operations',
            'access.dashboard',
            'access.manage.blocklist',
            'access.manage.locations',
            'access.manage.buildings',
            'access.manage.housing_units',
            'access.manage.residents',
            'access.manage.visitors',
            'access.manage.vehicles',
            'access.manage.vehicle_access',
            'access.register.entry',
            'access.register.exit',
            'access.manage.pre_authorizations',
            'access.manage.correspondence',
            'access.manage.guard_logs',
            'access.view.reports',
            'access.view.audit',
            'access.manage.turnos',
            'access.manage.zones',
        ],

        'anfitrion' => [
            'resident.portal.access',
            'access.manage.pre_authorizations',
            'client.zones.book',
        ],
    ],

    'navigation' => [
        'admin' => [
            'label' => 'Panel Plataforma',
            'permission' => 'platform.dashboard',
            'items' => [
                ['label' => 'Resumen', 'route' => 'admin.dashboard', 'permission' => 'platform.dashboard'],
                ['label' => 'Tabla de precios', 'route' => 'admin.pricing.edit', 'permission' => 'platform.companies.view'],
                ['label' => 'Empresas', 'route' => 'admin.companies.index', 'permission' => 'platform.companies.view'],
                ['label' => 'Usuarios', 'route' => 'admin.users.index', 'permission' => 'platform.users.view'],
                ['label' => 'Documentos', 'route' => 'admin.documents.index', 'permission' => 'platform.documents.view'],
                ['label' => 'Ajustes', 'route' => 'admin.settings.structure-types.index', 'permission' => 'platform.settings.manage'],
            ],
        ],
        'company' => [
            'label' => 'Panel Empresa',
            'permission' => 'company.dashboard',
            'items' => [
                ['label' => 'Mi empresa', 'route' => 'company.dashboard', 'permission' => 'company.dashboard'],
                ['label' => 'Facturación', 'route' => 'company.billing.index', 'permission' => 'company.dashboard'],
                ['label' => 'Clientes', 'route' => 'company.clients.index', 'permission' => 'company.clients.view'],
                ['label' => 'Supervisión', 'route' => 'company.supervision.index', 'permission' => 'company.supervision.view'],
                ['label' => 'Empleados', 'route' => 'company.employees.index', 'permission' => 'company.settings.manage'],
                ['label' => 'Usuarios', 'route' => 'company.users.index', 'permission' => 'company.users.assign'],
                ['label' => 'Mis datos', 'route' => 'company.settings.edit', 'permission' => 'company.settings.manage'],
                ['label' => 'Ajustes', 'route' => 'company.job-titles.index', 'permission' => 'company.settings.manage'],
            ],
        ],
        'access' => [
            'label' => 'Control Acceso',
            'permission' => 'access.dashboard',
            'items' => [
                ['label' => 'Operaciones', 'route' => 'access.operations', 'permission' => 'access.dashboard'],
                ['label' => 'Dashboard', 'route' => 'access.dashboard', 'permission' => 'access.dashboard'],
                ['label' => 'Ingreso/Salida', 'route' => 'access.logs.index', 'permission' => 'access.register.entry'],
                ['label' => 'Visitantes', 'route' => 'access.visitors.index', 'permission' => 'access.manage.visitors'],
                ['label' => 'Residentes', 'route' => 'access.residents.index', 'permission' => 'access.manage.residents'],
                ['label' => 'Apartamentos', 'route' => 'access.housing_units.index', 'permission' => 'access.manage.housing_units'],
                ['label' => 'Torres/Bloques', 'route' => 'access.buildings.index', 'permission' => 'access.manage.buildings'],
                ['label' => 'Vehículos', 'route' => 'access.vehicles.index', 'permission' => 'access.manage.vehicles'],
                ['label' => 'Control Vehicular', 'route' => 'access.vehicle_access.index', 'permission' => 'access.manage.vehicle_access'],
                ['label' => 'Pre-Autorizaciones', 'route' => 'access.pre_authorizations.index', 'permission' => 'access.manage.pre_authorizations'],
                ['label' => 'Correspondencia', 'route' => 'access.correspondence.index', 'permission' => 'access.manage.correspondence'],
                ['label' => 'Minutas', 'route' => 'access.guard_logs.index', 'permission' => 'access.manage.guard_logs'],
                ['label' => 'Turnos', 'route' => 'access.turnos.index', 'permission' => 'access.manage.turnos'],
                ['label' => 'Puntos de acceso', 'route' => 'access.locations.index', 'permission' => 'access.manage.locations'],
                ['label' => 'Lista Bloqueo', 'route' => 'access.blocklist.index', 'permission' => 'access.manage.blocklist'],
                ['label' => 'Zonas comunes', 'route' => 'access.zones.index', 'permission' => 'access.manage.zones'],
                ['label' => 'Auditoría', 'route' => 'access.audit.index', 'permission' => 'access.view.audit'],
                ['label' => 'Reportes', 'route' => 'access.reports.index', 'permission' => 'access.view.reports'],
            ],
        ],
        'client' => [
            'label' => 'Panel Conjunto',
            'permission' => 'client.structures.manage',
            'items' => [
                ['label' => 'Resumen', 'route' => 'client.dashboard', 'permission' => 'client.structures.manage'],
                ['label' => 'Estructura', 'route' => 'client.structures.index', 'permission' => 'client.structures.manage'],
                ['label' => 'Personas', 'route' => 'client.members.index', 'permission' => 'client.members.manage'],
                ['label' => 'Vehículos', 'route' => 'client.vehicles.index', 'permission' => 'client.vehicles.manage'],
                ['label' => 'Mascotas', 'route' => 'client.pets.index', 'permission' => 'client.pets.manage'],
                ['label' => 'Autorizaciones', 'route' => 'client.authorizations.index', 'permission' => 'client.authorizations.manage'],
                ['label' => 'Usuarios portal', 'route' => 'client.users.index', 'permission' => 'client.users.manage'],
                ['label' => 'Usuarios APP', 'route' => 'client.app-users.index', 'permission' => 'client.app_users.manage'],
                ['label' => 'Zonas comunes', 'route' => 'client.zones.index', 'permission' => 'client.zones.book'],
            ],
        ],
    ],

    'shifts' => [
        'enforced' => env('ACCESS_SHIFTS_ENFORCED', true),
        'daily_target_hours' => (float) env('ACCESS_SHIFTS_DAILY_TARGET_HOURS', 8.0),
    ],

    'geo' => [
        'required' => env('ACCESS_GEO_REQUIRED', true),
        'default_radius_m' => (int) env('ACCESS_GEO_RADIUS_M', 250),
    ],

    'alerts' => [
        'long_stay_hours' => (int) env('ACCESS_ALERT_LONG_STAY_HOURS', 12),
        'container_hours' => (int) env('ACCESS_ALERT_CONTAINER_HOURS', 24),
    ],

    'notifications' => [
        'email' => (bool) env('ACCESS_NOTIFICATIONS_EMAIL', false),
    ],
];
